name: GriefPreventionUtilities
version: ${project.version}
main: _112.griefpreventionutilities.GriefPreventionUtilities
depend: [GriefPrevention, FastAsyncWorldEdit]
authors: [_112]
description: Adding those little bits to GP that are niche use
commands:
  claimcleanup:
    permission: griefpreventionutils.claimcleanup
    description: Removes all claims where the owner has not logged in for your specified time
    usage: /claimcleanup <time> 
  saveclaims:
    permission: griefpreventionutils.saveclaims
    description: Copy all claims from <world1> to <world2> in the some spot. Be careful as no checks are done when the claim is pasted in
    usage: /saveclaims <world1> <world2>
  edeleteclaims:
    permission: griefpreventionutils.edeletaclaims
    description: Removes all claims inside your current WE selection
    usage: /edeleteclaims
  countclaims:
    permission: griefpreventionutils.countclaims
    description: Counts all claims inside your current WE selection
    usage: /countclaims
  deleteallunclaimed:
    permission: deleteallunclaimed
    description: Deletes all unclaimed chunks
